# Site Settings
title: Start Jekyll
email: stcastle@cs.washington.edu
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:4000"
twitter_username: samtcastle
github_username:  stcastle
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
